name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  # This triggers the action when you push to the 'main' branch

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code

    - name: Trigger Jenkins job
      run: |
        curl -X POST http://<your-jenkins-url>/github-webhook/ \
          -H "Content-Type: application/json" \
          -d '{"ref": "refs/heads/main"}'
